defaults: &defaults
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: ocn_development
  username: root
  password:

test:
  <<: *defaults
  database: ocn_test
  username: root
  password:

production:
  <<: *defaults
